repository:
  name: cv
  description: My C.V. as code -- in beta until !
  homepage: https://circleci.com/api/v1/project/TheKevJames/cv/latest/artifacts/0/$CIRCLE_ARTIFACTS/resume-elegant.html?branch=master&filter=successful
  private: false

  has_issues: true
  has_projects: false
  has_wiki: false

  allow_merge_commit: true
  allow_rebase_merge: true
  allow_squash_merge: true

labels:
  - name: bug
    color: fc2929
  - name: feature
    color: 84b6eb
    oldname: enhancement
  - name: help wanted
    color: 159818
  - name: low-priority
    color: fbca04
  - name: task
    color: d93f0b
  - name: question
    color: cc317c
  - name: backlog
    color: ededed
  - name: in-progress
    color: 0052cc
  - name: in-review
    color: 5319e7
