version: 2.1

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:470.0.0-alpine
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    resource_class: large
  node:
    docker:
      - image: node:21.7.1-alpine
    resource_class: large
  wkhtmltopdf:
    docker:
      - image: surnet/alpine-wkhtmltopdf:3.19.1-0.12.6-small
    resource_class: large

jobs:
  build:
    executor: node
    steps:
      - run: apk add -U make
      - checkout
      - run: npm ci
      - run: make test
      - run: make build/cv.html
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: build
          paths:
            - cv.html

  convert:
    executor: wkhtmltopdf
    steps:
      - attach_workspace:
          at: /tmp
      - run: mkdir build
      - run: wkhtmltopdf /tmp/cv.html build/cv.pdf
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: build
          paths:
            - cv.pdf

  upload:
    executor: gcloud
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gcloud storage cp build/cv.* gs://thekevjames-artifacts

workflows:
  run-jobs:
    jobs:
      - build
      - convert:
          requires:
            - build
      - upload:
          filters:
            branches:
              only: master
          requires:
            - convert
