version: 2.1

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:437.0.1
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
  node:
    docker:
      - image: node:20

jobs:
  build:
    executor: node
    steps:
      - run: apt-get update -qy
      - run: apt-get install -qy make
      - checkout
      - run: npm ci
      - run: make test
      - run: make
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: build
          paths:
            - cv.html
            - cv.pdf

  upload:
    executor: gcloud
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gcloud storage cp build/cv.* gs://thekevjames-artifacts

workflows:
  run-jobs:
    jobs:
      - build
      - upload:
          filters:
            branches:
              only: master
          requires:
            - build
