version: 2.1

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:437.0.1
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
  docker:
    docker:
      - image: docker:git
    environment:
      DOCKER_BUILDKIT: 1

jobs:
  build:
    executor: docker
    steps:
      - checkout
      - run: docker build --progress=plain -t cv:latest .
      - run:
          name: copy out build folder
          command: |
            img=$(docker create cv:latest)
            docker cp "${img}:/src/build" ./build
            docker rm -v "${img}"
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: build
          paths:
            - cv.html
            - cv.pdf

  upload:
    executor: gcloud
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gcloud storage cp build/cv.* gs://thekevjames-artifacts

workflows:
  run-jobs:
    jobs:
      - build
      - upload:
          filters:
            branches:
              only: master
          requires:
            - build
