version: 2.1

orbs:
  linter: thekevjames/linter@0.1

jobs:
  build-tex:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run: npm install hackmyresume
      - run: node_modules/.bin/hackmyresume build cv.json to build/cv.all -o options.json
      - run:
          name: clean latex build dir
          command: |
            mv build/latex/examples/cv* build/latex
            rm build/latex/.npmignore
            rm build/latex/Makefile
            rm build/latex/README.md
      - persist_to_workspace:
          root: build
          paths:
            - cv.json
            - cv.yml
            - latex/

  build-pdf:
    docker:
      - image: jpbernius/xelatex
    steps:
      - attach_workspace:
          at: build
      - run:
          name: xelatex build/latex/cv.tex
          command: |
            cd build/latex
            xelatex cv.tex
            mv cv.pdf ../
      - persist_to_workspace:
          root: build
          paths:
            - cv.pdf
      - store_artifacts:
          path: build/cv.pdf

  upload:
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run:
          name: authenticate with google cloud
          command: |
            echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gsutil -m cp build/cv.* gs://thekevjames-artifacts

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit:
          python_version: 3.7.4
      - build-tex
      - build-pdf:
          requires:
            - build-tex
      - upload:
          filters:
            branches:
              only: master
          requires:
            - build-tex
            - build-pdf
