version: 2.1

executors:
  gcloud:
    docker:
      - image: google/cloud-sdk:440.0.0-alpine
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /key.json
    resource_class: large
  node:
    docker:
      - image: node:20.5.1-alpine
    resource_class: large
  pandoc:
    docker:
      - image: pandoc/core:3.1.1
    resource_class: large

jobs:
  build:
    executor: node
    steps:
      - run: apk add -U make
      - checkout
      - run: npm ci
      - run: make test
      - run: make build/cv.html
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: build
          paths:
            - cv.html

  convert:
    executor: pandoc
    steps:
      - attach_workspace:
          at: /tmp
      - run: mkdir build
      - run: pandoc -obuild/cv.pdf /tmp/cv.html
      - store_artifacts:
          path: ./build
      - persist_to_workspace:
          root: build
          paths:
            - cv.pdf

  upload:
    executor: gcloud
    steps:
      - run: echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
      - run: gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gcloud storage cp build/cv.* gs://thekevjames-artifacts

workflows:
  run-jobs:
    jobs:
      - build
      - convert:
          requires:
            - build
      - upload:
          filters:
            branches:
              only: master
          requires:
            - convert
