version: 2.1

orbs:
  linter: talkiq/linter@3

jobs:
  build:
    docker:
      - image: node:19-alpine
    steps:
      - run: apk add -U make
      - checkout
      - run: npm ci
      - run: make test
      - run: make
      # - persist_to_workspace:
      #     root: build
      #     paths:
      #       - cv.pdf
      - store_artifacts:
          path: ./build

  upload:
    docker:
      - image: google/cloud-sdk
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /gcloud-service-key.json
    steps:
      - run:
          name: authenticate with google cloud
          command: |
            echo "${GCLOUD_SERVICE_KEY}" > "${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud auth activate-service-account --key-file="${GOOGLE_APPLICATION_CREDENTIALS}"
            gcloud config set project "thekevjames-175823"
      - attach_workspace:
          at: build
      - run: gsutil -m cp build/cv.* gs://thekevjames-artifacts

workflows:
  run-jobs:
    jobs:
      - linter/pre-commit
      - build
      # - upload:
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #       - build
